#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor

# Defining the text editor to use.
# DMENUEDITOR="st -e vim"
# DMENUEDITOR="st -e nvim"
DMEDITOR="st -e nvim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"awesome - $HOME/.config/awesome/rc.lua"
"bash - $HOME/.bashrc"
"dunst - $HOME/.config/dunst/dunstrc"
"dwm - $HOME/Documents/dwm/dwm/config.h"
"dwmblocks - $HOME/Documents/dwm/dwmblocks/blocks.h"
"dwmblocks-minimal - $HOME/Documents/dwm/dwmblocks-minimal/blocks.h"
"fish - $HOME/.config/fish/config.fish"
"i3 - $HOME/.i3/config"
"neovim - $HOME/.config/nvim/init.vim"
"picom - $HOME/.config/picom/picom.conf"
"qtile - $HOME/.config/qtile/config.py"
"quickmarks - $HOME/.config/qutebrowser/quickmarks"
"qutebrowser - $HOME/.config/qutebrowser/autoconfig.yml"
"st - $HOME/Documents/dwm/st/config.h"
"surf - $HOME/surf-distrotube/config.def.h"
"vifm - $HOME/.config/vifm/vifmrc"
"vim - $HOME/.vimrc"
"xmobar mon1  - $HOME/.config/xmobar/xmobarrc0"
"xmonad - $HOME/.xmonad/README.org"
"xresources - $HOME/.Xresources"
"zsh - $HOME/.zshrc"
"quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Edit config:')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 0

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
  # echo $DMEDITOR "$cfg"
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 0
fi
